
#ifndef SUDOKU_GENERATOR_SRC_SUDOKU_UTILS_H_
#define SUDOKU_GENERATOR_SRC_SUDOKU_UTILS_H_
typedef enum DIFFICULTY { EASY, MEDIUM, HARD, VERYHARD, IMPOSSIBLE } DIFFICULTY;
#endif //SUDOKU_GENERATOR_SRC_SUDOKU_UTILS_H_
